language: python
services:
  - docker
python:
- '3.7'

before_install:
  - pip install -r requirements.txt
  - chmod +x build.py

stages:
  - name: test
    if: type = pull_request
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: test
      script: ./build.py --test
    - stage: deploy
      script: ./build.py --test --push --userenv QUAY_USERNAME --passwordenv QUAY_PASSWORD
