name: build-containers
on:
  push:
    branches:
      - master
jobs:
  build-containers:
    runs-on: ubuntu-latest
    environment:  build_containers
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: install pip reqs
        run: pip install -r requirements.txt
      - name: run build test script
        run: python build.py --test --push --userenv QUAY_USERNAME --passwordenv QUAY_PASSWORD
        env: 
          QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
          QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
