name: test-containers
on: [pull_request]
jobs:
  test-containers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: install pip reqs
        run: pip install -r requirements.txt
      - name: run build test script
        run: python build.py --test